version: '3.8'

services:

  docker-daemon:
    image: docker:dind
    container_name: docker-daemon
    environment:
      DOCKER_TLS_CERTDIR: ""
    networks:
      docker-net:
        aliases:
          - docker
    privileged: true


  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      docker-net: { }

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pwd
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      docker-net: { }

  web:
    build: .
    container_name: docker_rest_app-server
    ports:
      - "8080:8080"
    command: python docker_rest_app/__main__.py
    environment:
      #      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://user:pwd@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DOCKER_HOST=tcp://docker:2375
    depends_on:
      - redis
      - rabbitmq
    networks:
      docker-net: { }

  celery-worker-1:
    build: .
    container_name: celery-worker-1
    privileged: true
    command: python docker_rest_app/celery_app/__main__.py TUX-Polaris@worker-1
    environment:
      #      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://user:pwd@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DOCKER_REGISTRY_URL=ghcr.io/abdulmateen59/async-docker-rest-app
      - DOCKER_REGISTRY_USERNAME=abdulmateen59
      - DOCKER_REGISTRY_PASSWORD=iAmDummyTokenReplaceMe
      - DOCKER_HOST=tcp://docker:2375
    depends_on:
      - redis
      - rabbitmq
    networks:
      docker-net: { }

  celery-worker-2:
    build: .
    container_name: celery-worker-2
    privileged: true
    command: python docker_rest_app/celery_app/__main__.py TUX-Polaris@worker-2
    environment:
      #      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://user:pwd@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DOCKER_REGISTRY_URL=ghcr.io/abdulmateen59/async-docker-rest-app
      - DOCKER_REGISTRY_USERNAME=abdulmateen59
      - DOCKER_REGISTRY_PASSWORD=iAmDummyTokenReplaceMe
      - DOCKER_HOST=tcp://docker:2375
    depends_on:
      - redis
      - rabbitmq
    networks:
      docker-net: { }


  celerybeat:
    build: .
    container_name: celerybeat
    privileged: true
    command: celery --app=docker_rest_app.celery_app beat -l info
    environment:
      #      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://user:pwd@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DOCKER_REGISTRY_URL=ghcr.io/abdulmateen59/async-docker-rest-app
      - DOCKER_REGISTRY_USERNAME=abdulmateen59
      - DOCKER_REGISTRY_PASSWORD=iAmDummyTokenReplaceMe
      - DOCKER_HOST=tcp://docker:2375
    depends_on:
      - redis
      - rabbitmq
    networks:
      docker-net: { }


  dashboard:
    build: .
    container_name: dashboard
    command: >
      sh -c "sleep 03 && 
             celery --app=docker_rest_app.celery_app flower --port=5555 --broker=amqp://user:pwd@0.0.0.0:5672/"
    ports:
      - "5555:5555"
    environment:
      # - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://user:pwd@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - celery-worker-1
      - celery-worker-2
      - rabbitmq
      - redis
    networks:
      docker-net: { }

networks:
  docker-net:
    name: docker-net